version: '3.1'
services:
  odoo:
    image: "ghcr.io/m3r3nix/odoo-v17-community:latest"
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ../:/workspace
      - ../custom:/mnt/extra-addons
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
